### ISSUE TITLE
How to customize the Quick Start

### ISSUE THREAD

**Issue by istiaquem** [aws-quickstart/quickstart-amazon-eks#12]
How do I create a new parameter, for example, specify user-defined EKS Name. Passing parameter in the template like another CFN template does not seem to work. Are there any restrictions on parameters to be passed?

**Comment by jaymccon** [comment]
To pass parameters to the Control plane stack you add parameter here https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks.template.yaml#L290, and to the Control plane template itself.

Out of interest, what is the use-case for needing a user provided cluster name ?

**Comment by istiaquem** [comment]
Thank you for the response. I have created codepipeline and called amazon-eks-master.template in my buildspec.yml. Works fine, creates EKS cluster with all other resources. But I have a requirement to follow naming conventions for EKS Name.  Per your guidelines, I have added parameter EksName in https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks.template.yaml#L290 and used in the control plane template, also used it as follows:
Resources:
  EKS:
    Type: "AWS::EKS::Cluster"
    Properties:
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
      RoleArn: !Ref RoleArn
      Version: !Ref KubernetesVersion
      **Name: !Ref EksName**

 But looks like it is ignoring that and creates a cluster with some generic names like EKS-AFilrP7pVpC7.

Any thoughts?

**Comment by jaymccon** [comment]
There are no restrictions/validataion on how parameters are passed to the control plane stack, the whole lot are simply passed on as is. https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/functions/source/CfnStackAssumeRole/lambda_function.py#L210-L214

Can you share your modified templates so we can have a look ?

With regards to naming conventions, it is standard practice for CloudFormation to generate names for resources, and not doing so can result in stacks failing due to duplicate names, as well as loosing the ability to update properties that require replacement (haven't tested whether this is the case for EKS though). If at all possible, I would suggest using tags to provide identifiers rather than names.

**Comment by jaymccon** [comment]
just taking a 2nd look at this, @istiaquem have you uploaded all of the templates to your own bucket and then pointed the QSS3Bucket and QSS3Prefix parameters to your new location ? if this is not done then the child stacks will continue to use the templates in our public bucket, which could cause the symptoms you are experiencing .

**Comment by istiaquem** [comment]
@jaymccon you are right. I did not upload templates to my bucket but was running against your default bucket.  Creating a new bucket, copying all /templates and adding it as parameter should work?

amazon-eks-defaults.json
[
  {
    "ParameterKey": "KeyPairName",
    "ParameterValue": "override"
  },
  {
    "ParameterKey": "RemoteAccessCIDR",
    "ParameterValue": "10.0.0.0/16"
  },
  {
    "ParameterKey": "AvailabilityZones",
    "ParameterValue": "$[taskcat_genaz_3]"
  },
  {
    "ParameterKey": "QSS3BucketName",
    "ParameterValue": "caasdemo"
  },
  {
    "ParameterKey": "AdditionalEKSAdminArns",
    "ParameterValue": ""
  }
]

**Comment by jaymccon** [comment]
For more details on how to customize this project have a look at the [AWS Quick Start contributors guide](https://aws-quickstart.github.io/option1.html).

**Comment by istiaquem** [comment]
thank you
