### ISSUE TITLE
Template Update Error

### ISSUE THREAD

**Issue by mbiokyle29** [aws-quickstart/quickstart-amazon-eks#141]
I am using the EKS quickstart cloud formation template and getting an error when I try to make updates to my stack. The error started happening after I completed the setup (in AWS and eks/k8s) of a persistent volume backed by EKS.

The error I am getting when I run `aws cloudformation update-stack` is:
```
Update of resource type is not permitted. The new template modifies resource type of the following resources: [EFSProvisioner]
```
This error occurs with in the nested `EKSStack` stack, on the resource with ID: `EfsStack`

Wondering if anyone has seen anything else like this?

**Comment by jaymccon** [comment]
@mbiokyle29 this is likely due to changes in https://github.com/aws-quickstart/quickstart-amazon-eks/commit/842c82e5a3264bf53c5070897817bc497d838532 that implement the newer CloudFormation Registry type for helm, which replaces the "Custom::Helm" custom resource used previously. 

To continue to update your stack safely I'd suggest pushing the [final v1.0 release](https://github.com/aws-quickstart/quickstart-amazon-eks/releases/tag/v1.0-final) to your own S3 bucket, and then doing a stack update, changing the QSS3Bucket parameter to reflect your bucket name.
