### ISSUE TITLE
Referencing quickstart-amazon-eks in another quickstart

### ISSUE THREAD

**Issue by kolomied** [aws-quickstart/quickstart-amazon-eks#228]
My understanding is that `main` branch of a quickstart should contain **all** files/resources required to successfully deploy the quickstart. Submodule referencing model works only because of this assumption - as a user of a quickstart I rely on a huge tree of submodules and expect that all files are present when I clone a repository.

## Current behavior

I believe this is not the case with `quickstart-amazon-eks` - for example, `main` branch does not contain packaged lambda functions that have to be built manually using the scripts provided. That may be OK if all I want is a customization of `quickstart-amazon-eks`. However, it does not work at all if I build a new quickstart and reference `quickstart-amazon-eks` as a submodule.

## Expected behavior
Packaged lambda functions are available in `main` branch.  `quickstart-amazon-eks` can be referenced as a submodule as a foundation for other quickstarts.

Please verify my understanding, I may be missing something trivial here.

**Comment by gargana** [comment]
Typically these are built as part of our CI/CD process which we use to test and deploy Quick Starts to our public S3 buckets where our catalog of Quick Starts are launched from.

We make use of [Taskcat](https://github.com/aws-quickstart/taskcat) to build and upload these final artifacts to our production buckets.

[Taskcat](https://pypi.org/project/taskcat/) can recursively build all of these artifacts an it recurses through submodules as part of its build process.

This [workshop](https://taskcat.github.io/workshop/) may be useful in order to get you up and running with it.

Another useful Taskcat resource can be found here: https://aws-quickstart.github.io/taskcat/ 

There are existing Quick Starts that consume the EKS Quick Start in the fashion you describe such as [Kubesphere](https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere).

You can take a look at that projects [.taskcat.yml](https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere/blob/main/.taskcat.yml) to get a starting config for Taskcat.

There is also a QuickStart aimed at getting a CI/CD setup in place for developing using Taskcat [here](https://github.com/aws-quickstart/quickstart-taskcat-ci). 

The Makefile and scripts provided in this repo are a _convenience_ for users who wish to build the EKS Quick Start without the overhead of having to learn Taskcat.

Let me know if I can assist further.

**Comment by kolomied** [comment]
Great feedback @gargana, really appreciate all the pointers! I wish I saw something like this in official quickstart docs :)
Thanks, I think we can safely close this issue.
