### ISSUE TITLE
Depreation python cloudformation library

### ISSUE THREAD

**Issue by jorgenivia** [aws-quickstart/quickstart-amazon-eks#279]
Hi,

I would like to confirm if the new versions of this quickstart  (cloudformation) handle the **botocore.requests** library, since aws sent a message informing the deprecation of this component.

thanks

**Comment by cwardcode** [comment]
I'm curious to know as well. We've been receiving reminders about this in our accounts, and the deadline (April 01) is coming up fast.

**Comment by cwardcode** [comment]
Just wanted to update this and say that this should only be an issue for existing deployments. 

According to this AWS KB [article](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-cfn-response-lambda/):

```
The cfn-response module code example uses botocore.requests in the Lambda function’s deployment package.
To update the cfn-response module to the latest version that uses urllib3, update the function’s inline code in the AWS CloudFormation template. Do this by adding a comment to the inline Lambda function’s code. For example:
ZipFile: |
           import cfnresponse
           def handler(event, context):
+            # This comment was added to force an update on this function's code
             responseData = {'Message': 'Hello {}!'.format(event['ResourceProperties']['Name'])}
             cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "CustomResourcePhysicalID")
```

I've had a cloned copy of the repo because the quickstart changes so much and may introduce breaking changes, updating based on the template URL tends to be unreliable. 

In my case, I'll have to update the in-line lambdas myself, re-upload the templates to S3, then redeploy my EKS stack.
