### ISSUE TITLE
Passwordless SUDO from ssm-user no longer supported

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-amazon-eks#415]
One of our SAs discovered that you can no longer sudo from ssm-user without a password.

This complicates installing docker for the GItLab scenarios I use this for.

Is it worth adding a parameter for bastion host to reenable this?

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-ssm-user-permissions.html

**Comment by tlindsay42** [comment]
Decided to grant `ssm-user` passwordless sudo by default in the built-in bootstrap script so that users aren't surprised by insufficient privileges when they need access- particularly since SSM-only is the default now. Customers that prefer otherwise can override using the [`BastionBootstrapScript` parameter via the advanced config stack](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/2dae3c52e5d0674d55a1f269a20637da5d33fe57/templates/amazon-eks-advanced-configuration.template.yaml#L215). Thanks as always for your great ideas, patience, & partnership, @DarwinJS!

Note: This isn't deployed yet due to an unrelated bug, but it should be soon. I'll leave this open until then.
