### ISSUE TITLE
Cluster Cleanup No Longer Works

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-amazon-eks#418]
I've tested this many times and persistently get this error on teardown (and on each additional attempt to teardown in the console):

![Screen Shot 2022-05-07 at 8 54 20 AM](https://user-images.githubusercontent.com/11597190/167255325-e06720b3-5cac-4efb-a12a-d25e75894f22.png)

And on manual teardown of the VPC, I persistently get this security group deletion warning - and it is the only resource warning once the teardown has run at least once.

![Screen Shot 2022-05-07 at 8 54 52 AM](https://user-images.githubusercontent.com/11597190/167255351-accfeb6f-4f33-4b51-adc1-e69974af6d71.png)

After the manual VPC delete the stack tears down properly

Perhaps a new security group was added recently and it was not added to cleanup lambdas?

**Comment by satya-dillikar** [comment]
[quickstart-vmware-tanzu-application-platform](https://github.com/satya-dillikar/quickstart-vmware-tanzu-application-platform) needs this fix. Thanks.

**Comment by jagane-infinstor** [comment]
I have encountered this bug as well. It looks like the Network Interfaces in the VPC are not deleting. They have a description like this:
AWS Lambda VPC ENI-helm-provider-vpc-connector-e98a06e7baa4c116475f0be2b5fd36fb-beef7a2b-67b9-4df0-9ec6-c6dd5b67cec3

I am unable to delete the vpc manually because of this network attachment.

**Comment by jagane-infinstor** [comment]
Here's some more information. CloudWatch has the following entry in the Log Group /aws/lambda/eks-quickstart-CleanupSecurityGroupDependencies:

ERROR: eni-0c639e2844e2f3e8e An error occurred (OperationNotPermitted) when calling the DetachNetworkInterface operation: You are not allowed to manage 'ela-attach' attachments.

**Comment by jagane-infinstor** [comment]
OK, I may have one piece of useful information - I created a stack without the bastion host and deletion of this stack went smoothly. The RegionalSharedResources and the AccountSharedResources stacks were left behind, but that is by design, right? I was able to create and delete a stack without the bastion host two times in a row - us-east-2, 3 t3.medium worker nodes.

@satya-dillikar @DarwinJS - can you try creating a stack without a bastion host and let us know if that works?

Maybe there is some timing issue with deletion when a bastion host is present? Hope this helps @tlindsay42

**Comment by tlindsay42** [comment]
Very helpful. Thanks @jagane-infinstor!

**Comment by DarwinJS** [comment]
Still having this problem with the latest GitLab QSG. Perhaps the CI tests do not include "clean delete" after a "create with new VPC" template is used?
![Screen Shot 2022-09-02 at 11 07 27 AM](https://user-images.githubusercontent.com/11597190/188179844-d59926f3-e492-4121-a46e-099bee471613.png)
