### ISSUE TITLE
What is the best approach for adding permissions to the instance profiles?

### ISSUE THREAD

**Issue by autodidacticon** [aws-quickstart/quickstart-amazon-eks#436]
Both of `ManagedNodeInstanceRole` and `UnmanagedNodeInstanceRole` are provisioned via the `AccountSharedResources` stack.

If additional permissions needed to be added to either of these roles what is the best approach?

Currently I have modified the `AccountSharedResources` stack after it has been provisioned but it seemingly can be overwritten when additional K8s clusters are deployed via the quickstart parent stack.

**Comment by tlindsay42** [comment]
Hi @autodidacticon, and sorry for the delay. This is how it was implemented in [GitLab's project](https://github.com/aws-quickstart/quickstart-eks-gitlab/commit/eb336245f5226326c6d640ce915ade9eeedae035); however, we had to remove it as shown in the referenced commit because it limits the number of clusters you can deploy per account since each IAM Role has a maximum policy document length, and each new cluster will attach a new policy to the shared Role- contributing to the policy document length. If this is acceptable for your use case, go for it; however, I recommend documenting this limitation/warning as part of the design decision, as it can be difficult to troubleshoot- particularly in CI environments.
