### ISSUE TITLE
CloudFormation fail on GetCallerArn Lambda function

### ISSUE THREAD

**Issue by zoopster** [aws-quickstart/quickstart-amazon-eks#53]
Can we apply the fix for issue #48 to the SUSE quickstart for CAP? I'm getting the same error.

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.
