### ISSUE TITLE
Suggested Upgrade Process

### ISSUE THREAD

**Issue by maguire007** [aws-quickstart/quickstart-amazon-eks#55]
What's the suggested and recommended way to update the EKS quickstart cloudformation with new changes that are committed ranging from  say you want to upgrade EKS K8 version or new bastion host cf changes?  Any insight would be appreciated.

**Comment by schottsfired** [comment]
Hi @maguire007, I recently added an "Upgrades" section to the CloudBees Core on AWS Quick Start [deployment guide](https://aws-quickstart.s3.amazonaws.com/quickstart-cloudbees-core/doc/cloudbees-core-on-the-aws-cloud.pdf) (page 23). I hope it helps to answer your question!

**Comment by maguire007** [comment]
Very helpful.  Thank you.

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.
