### ISSUE TITLE
AddCallerUserToClusterAsAdmin - Failed to create resource. 'root'

### ISSUE THREAD

**Issue by dhiman-halder** [aws-quickstart/quickstart-amazon-eks#60]
While running the Quickstart CFN template receiving the following error

In the stack for creating the Control Plane I always get the following error:

CREATE_FAILED | Custom::KubeManifest | AddCallerUserToClusterAsAdmin | Failed to create resource. 'root'

**Comment by tomiszili** [comment]
@dhiman-halder 
Don't use this template from root of your account it is not so elegant. Make a new user with the needed policies, and run from that user as the best practice suggests.

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.
