### ISSUE TITLE
Syntax error in quickstart-amazon-eks/functions/packages/KubeManifest/lambda.zip

### ISSUE THREAD

**Issue by brcourt** [aws-quickstart/quickstart-amazon-eks#62]
Line no. 39 in lambda_function.py, while handling an exception, the string format method is applied to a Logger instead of a String.

```
39 |         logger.debug("{}, retrying in 5 seconds").format(e)
```

should instead be typed:

```
39 |         logger.debug("{}, retrying in 5 seconds".format(e))
```

I would also like to suggest refactoring this lambda code. The **run_command** function is especially confusing, and the error handling is unnecessarily complex.

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.
