### ISSUE TITLE
The EKSControlPlane not signalling proberly if it is sucessfully created.

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#68]
I changed my NodeGroupStack in the [amazon-eks-template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks.template.yaml#L258-L282) to https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml template and i made minor modifications in the input parameters to integrate the new stack. But with the new template `ClusterName` parameter cannot be resolved with `!Ref EKSContolPlane.EKSName`  according to CloudFormation error.
<img width="581" alt="2019-11-07_12h22_44" src="https://user-images.githubusercontent.com/54439475/68385088-52238c80-0159-11ea-8735-e1fd10c498c0.png">

How can it work with the current nested nodegroup stack [amazon-eks-template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks.template.yaml#L258-L282) ?

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.
