### ISSUE TITLE
Add ALB Ingress controller to quickstart for EKS 

### ISSUE THREAD

**Issue by troy-ameigh** [aws-quickstart/quickstart-amazon-eks#86]
Please add ALB Ingress controller functionality to quickstart.

**Comment by sukrit007** [comment]
This one is definitely tricky using cloudformation.  I ended up creating custom resources to deploy this. 
1.  Configure OIDC Provider using custom cloudformation stack:  https://github.com/intraedge-services/aws-ms-eks-reference/blob/master/cloudformation/eks-oidc-provider.yaml
2. Use the provider url to configure ALB Ingress controller:
https://github.com/intraedge-services/aws-ms-eks-reference/blob/master/cloudformation/eks-alb-ingress-controller.yaml
3. Add annotation to your VPC:
https://github.com/intraedge-services/aws-ms-eks-reference/blob/master/cloudformation/eks-app-stack.yml#L117

The full example can be found at: 
https://github.com/intraedge-services/aws-ms-eks-reference/blob/master/cloudformation/eks-app-stack.yml

The entire setup is based on:
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

If AWS Team likes the approach,  I can bundle this into quickstart and submit a PR.

**Comment by phenri00** [comment]
I know the documentation says we need to create a  IAM OIDC identity provider. But why do we need to create it as an extra step? Isn't it created as default with the latest versions(1.13 ->)? And why do the ALB need it?

Im confused :-)

**Comment by sukrit007** [comment]
> IAM OIDC identity provider

- IAM OIDC Identity provider is needed to allow Kubernetes service roles to assume IAM roles. Previously, you had to use IAM roles on ec2 instance so any service running in Kubernetes had access to the instance.  With the new approach,  you can associate IAM roles for every Kubernetes deployment running in the cluster.  In this specific case,  we are creating a service account for ALB Ingress controller  and associating it with IAM Role so that the controller can create/manage ALB when ingress rules are added.
- I did not see automatic creation of  IAM OIDC Identity in Kubernetes 1.15.  I do know OIDC is enabled by default in these versions,  but we still have to activate the IAM OIDC Identity provider so that the service role can assume federated IAM Role.

**Comment by phenri00** [comment]
Great. Thanks for clarification.

**Comment by ThisIsQasim** [comment]
@jaymccon we can close this now
